### ISSUE TITLE
Use with Controller Credentials

### ISSUE THREAD

**Issue by dkolepp** [ansible-middleware/redhat-csp-download#25]
##### SUMMARY

It's not clear how the role or module can utilize a Controller credential, other than a "Vault" credential to unlock an encrypted value from a file.  Is there any documentation / guidance on how to use Controller credentials with this collection?  Other collections, like `ansible.controller` also use environment variables to pull in Controller authentication secrets - which are provided by the Red Hat Ansible Automation Platform Credential (type).

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

N/A

##### COLLECTION VERSION

```
v1.2.1
```

##### STEPS TO REPRODUCE

NA

##### EXPECTED RESULTS

Expect a way to pass in secrets to the role/module, using certain Environment variables and/or known (local) configuration - like those found in the `cloud.openstack` modules - so that Controller Credentials can be associated with playbook to create an appropriate Job Template.

If there were a set of associated environment variables, or an expected (configuration) file - then an custom Credential Type could created/used/provided - to store an appropriate credential to associate with role when used in a playbook.

##### ACTUAL RESULTS

N/A

**Comment by sabre1041** [comment]
@dkolepp Thanks for the issue.

How does the following environment variables sound?

* `REDHAT_CSP_USERNAME`
* `REDHAT_CSP_PASSWORD`

**Comment by dkolepp** [comment]
As a side note - what are the release plans, so that it is visible in Red Hat AutomationHub ?
![image](https://user-images.githubusercontent.com/10145457/167144011-d69370ba-8a33-4c23-bba4-9fcf96ac440f.png)
